services:
  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    restart: no
    volumes:
      - ./conf:/etc/letsencrypt
      - ./data:/var/lib/letsencrypt
      - ./log:/var/log/letsencrypt
      - ./apikey.ini:/secrets/apikey.ini:ro
    command:
      - certonly
      - --dns-cloudflare
      - --dns-cloudflare-credentials
      - /secrets/apikey.ini
      - --dns-cloudflare-propagation-seconds
      - '60'
      - --force-renewal
      - --non-interactive
      - --agree-tos
      - --email
      - example@example.com
      - -d
      - example.com
      - -d
      - www.example.com
